// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0wall110 = new Entity("lv0_wall(1)")
engine.addEntity(lv0wall110)
const lv0wall110transform = new Transform({
  position: new Vector3(8.331, 2.5, 0.118),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(15, 5, 0.15)
})
lv0wall110.addComponentOrReplace(lv0wall110transform)
const lv0wall110boxShape = new BoxShape()
lv0wall110.addComponentOrReplace(lv0wall110boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0wall211 = new Entity("lv0_wall(2)")
engine.addEntity(lv0wall211)
const lv0wall211transform = new Transform({
  position: new Vector3(15.76098, 2.5, 8.015213),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(15.625, 5, 0.027)
})
lv0wall211.addComponentOrReplace(lv0wall211transform)
const lv0wall211boxShape = new BoxShape()
lv0wall211.addComponentOrReplace(lv0wall211boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0wall312 = new Entity("lv0_wall(3)")
engine.addEntity(lv0wall312)
const lv0wall312transform = new Transform({
  position: new Vector3(8.389, 2.5, 15.901),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(15, 5, 0.15)
})
lv0wall312.addComponentOrReplace(lv0wall312transform)
const lv0wall312boxShape = new BoxShape()
lv0wall312.addComponentOrReplace(lv0wall312boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const qrPoster76 = new Entity("QR Poster")
engine.addEntity(qrPoster76)
const qrPoster76transform = new Transform({
  position: new Vector3(6.745915, 0, 7.979295),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
qrPoster76.addComponentOrReplace(qrPoster76transform)
const qrPoster76GLTFShape = new GLTFShape("1206a867-819a-40ce-a397-ee8dce04d35a/models/QR_Poster.glb")
qrPoster76GLTFShape.withCollisions = true
qrPoster76GLTFShape.isPointerBlocker = true
qrPoster76GLTFShape.visible = true
qrPoster76.addComponentOrReplace(qrPoster76GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1return87 = new Entity("lv1_return")
engine.addEntity(lv1return87)
const lv1return87transform = new Transform({
  position: new Vector3(-10.691, 1.04, 0.289),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.041992, 1, 0.214)
})
lv1return87.addComponentOrReplace(lv1return87transform)
const lv1return87GLTFShape = new GLTFShape("846479b0-75d3-450d-bbd6-7e6b3355a7a2/models/ClickAreaDummy.glb")
lv1return87GLTFShape.withCollisions = true
lv1return87GLTFShape.isPointerBlocker = true
lv1return87GLTFShape.visible = true
lv1return87.addComponentOrReplace(lv1return87GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1floor89 = new Entity("lv1_floor")
engine.addEntity(lv1floor89)
const lv1floor89transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
lv1floor89.addComponentOrReplace(lv1floor89transform)
const lv1floor89GLTFShape = new GLTFShape("9be6610f-cf2b-47fc-a5bd-c9aa62ea6f8e/FloorFantasyRocks_01/FloorFantasyRocks_01.glb")
lv1floor89GLTFShape.withCollisions = true
lv1floor89GLTFShape.isPointerBlocker = true
lv1floor89GLTFShape.visible = true
lv1floor89.addComponentOrReplace(lv1floor89GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1deadlyobstacle190 = new Entity("lv1_deadlyobstacle(1)")
engine.addEntity(lv1deadlyobstacle190)
const lv1deadlyobstacle190transform = new Transform({
  position: new Vector3(12.848, 2.947, 8),
  rotation: new Quaternion(-0.4925276, -0.5073624, -0.4925276, 0.5073624),
  scale: new Vector3(1, 1, 4.09)
})
lv1deadlyobstacle190.addComponentOrReplace(lv1deadlyobstacle190transform)
const lv1deadlyobstacle190GLTFShape = new GLTFShape("6631a0b6-3eb3-4cca-b777-95c5083ead08/Sword_01/Sword_01.glb")
lv1deadlyobstacle190GLTFShape.withCollisions = true
lv1deadlyobstacle190GLTFShape.isPointerBlocker = true
lv1deadlyobstacle190GLTFShape.visible = true
lv1deadlyobstacle190.addComponentOrReplace(lv1deadlyobstacle190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1deadlyobstacle492 = new Entity("lv1_deadlyobstacle(4)")
engine.addEntity(lv1deadlyobstacle492)
const lv1deadlyobstacle492transform = new Transform({
  position: new Vector3(4.607, 2.947, 8),
  rotation: new Quaternion(-0.4925276, -0.5073624, -0.4925276, 0.5073624),
  scale: new Vector3(1, 1, 4.09)
})
lv1deadlyobstacle492.addComponentOrReplace(lv1deadlyobstacle492transform)
lv1deadlyobstacle492.addComponentOrReplace(lv1deadlyobstacle190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1deadlyobstacle293 = new Entity("lv1_deadlyobstacle(2)")
engine.addEntity(lv1deadlyobstacle293)
const lv1deadlyobstacle293transform = new Transform({
  position: new Vector3(10.996, 2.947, 8),
  rotation: new Quaternion(-0.4925276, -0.5073624, -0.4925276, 0.5073624),
  scale: new Vector3(1, 1, 4.09)
})
lv1deadlyobstacle293.addComponentOrReplace(lv1deadlyobstacle293transform)
lv1deadlyobstacle293.addComponentOrReplace(lv1deadlyobstacle190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1deadlyobstacle594 = new Entity("lv1_deadlyobstacle(5)")
engine.addEntity(lv1deadlyobstacle594)
const lv1deadlyobstacle594transform = new Transform({
  position: new Vector3(3.074, 2.947, 8),
  rotation: new Quaternion(-0.4925276, -0.5073624, -0.4925276, 0.5073624),
  scale: new Vector3(1, 1, 4.09)
})
lv1deadlyobstacle594.addComponentOrReplace(lv1deadlyobstacle594transform)
lv1deadlyobstacle594.addComponentOrReplace(lv1deadlyobstacle190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1fence297 = new Entity("lv1_fence(2)")
engine.addEntity(lv1fence297)
const lv1fence297transform = new Transform({
  position: new Vector3(7.029, 0.171, 2.372),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(5, 5, 5)
})
lv1fence297.addComponentOrReplace(lv1fence297transform)
const lv1fence297GLTFShape = new GLTFShape("dc33fcb8-1405-4226-a5c4-a38513ac6605/Fence_Stone_Block_02/Fence_Stone_Block_02.glb")
lv1fence297GLTFShape.withCollisions = true
lv1fence297GLTFShape.isPointerBlocker = true
lv1fence297GLTFShape.visible = true
lv1fence297.addComponentOrReplace(lv1fence297GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1fence199 = new Entity("lv1_fence(1)")
engine.addEntity(lv1fence199)
const lv1fence199transform = new Transform({
  position: new Vector3(7.029, 0.171, 12.657),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(5, 5, 5)
})
lv1fence199.addComponentOrReplace(lv1fence199transform)
lv1fence199.addComponentOrReplace(lv1fence297GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1fence4100 = new Entity("lv1_fence(4)")
engine.addEntity(lv1fence4100)
const lv1fence4100transform = new Transform({
  position: new Vector3(7.029, 0.171, 8.978),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(5, 5, 5)
})
lv1fence4100.addComponentOrReplace(lv1fence4100transform)
lv1fence4100.addComponentOrReplace(lv1fence297GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1fence3101 = new Entity("lv1_fence(3)")
engine.addEntity(lv1fence3101)
const lv1fence3101transform = new Transform({
  position: new Vector3(7.029, 0.171, 5.345),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(5, 5, 5)
})
lv1fence3101.addComponentOrReplace(lv1fence3101transform)
lv1fence3101.addComponentOrReplace(lv1fence297GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2moveableppiece1114 = new Entity("lv2_moveableppiece(1)")
engine.addEntity(lv2moveableppiece1114)
const lv2moveableppiece1114transform = new Transform({
  position: new Vector3(10.238, 2.203, 0.3),
  rotation: new Quaternion(0.7071068, 0, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
lv2moveableppiece1114.addComponentOrReplace(lv2moveableppiece1114transform)
const lv2moveableppiece1114GLTFShape = new GLTFShape("dba7c6c8-4b41-409e-88b3-84178ec417ce/LightBlock_02/LightBlock_02.glb")
lv2moveableppiece1114GLTFShape.withCollisions = true
lv2moveableppiece1114GLTFShape.isPointerBlocker = true
lv2moveableppiece1114GLTFShape.visible = true
lv2moveableppiece1114.addComponentOrReplace(lv2moveableppiece1114GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2ppiece1115 = new Entity("lv2_ppiece(1)")
engine.addEntity(lv2ppiece1115)
const lv2ppiece1115transform = new Transform({
  position: new Vector3(8.205, 2.02, 0.3),
  rotation: new Quaternion(0.5013073, -0.4986893, -0.4986893, 0.5013073),
  scale: new Vector3(1, 1, 1)
})
lv2ppiece1115.addComponentOrReplace(lv2ppiece1115transform)
const lv2ppiece1115GLTFShape = new GLTFShape("0fbe386e-cc30-4ce9-8eb6-d78101ff090b/LightCorner_02/LightCorner_02.glb")
lv2ppiece1115GLTFShape.withCollisions = true
lv2ppiece1115GLTFShape.isPointerBlocker = true
lv2ppiece1115GLTFShape.visible = true
lv2ppiece1115.addComponentOrReplace(lv2ppiece1115GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2ppiece2118 = new Entity("lv2_ppiece(2)")
engine.addEntity(lv2ppiece2118)
const lv2ppiece2118transform = new Transform({
  position: new Vector3(11.903, 2.622, 0.510134),
  rotation: new Quaternion(0, 0, 0.9999619, 0.008726561),
  scale: new Vector3(1, 1, 1)
})
lv2ppiece2118.addComponentOrReplace(lv2ppiece2118transform)
const lv2ppiece2118GLTFShape = new GLTFShape("28352c3a-cc20-4ab4-b4b8-a4562a6b0d4d/models/signpost/Sign_Arrow.glb")
lv2ppiece2118GLTFShape.withCollisions = true
lv2ppiece2118GLTFShape.isPointerBlocker = true
lv2ppiece2118GLTFShape.visible = true
lv2ppiece2118.addComponentOrReplace(lv2ppiece2118GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2ppiece3119 = new Entity("lv2_ppiece(3)")
engine.addEntity(lv2ppiece3119)
const lv2ppiece3119transform = new Transform({
  position: new Vector3(13.642, 1.555, 0.431),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
lv2ppiece3119.addComponentOrReplace(lv2ppiece3119transform)
const lv2ppiece3119GLTFShape = new GLTFShape("80e32415-fcd9-40d2-a322-f046d8249eb4/models/signpost/Sign_Circle.glb")
lv2ppiece3119GLTFShape.withCollisions = true
lv2ppiece3119GLTFShape.isPointerBlocker = true
lv2ppiece3119GLTFShape.visible = true
lv2ppiece3119.addComponentOrReplace(lv2ppiece3119GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2wall1128 = new Entity("lv2_wall(1)")
engine.addEntity(lv2wall1128)
const lv2wall1128transform = new Transform({
  position: new Vector3(15.759, 0, 15.854),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(6.872, 1.233, 1)
})
lv2wall1128.addComponentOrReplace(lv2wall1128transform)
const lv2wall1128GLTFShape = new GLTFShape("53aa3052-ccd7-4a05-be3f-f840acbff99e/Concrete_Wall.glb")
lv2wall1128GLTFShape.withCollisions = true
lv2wall1128GLTFShape.isPointerBlocker = true
lv2wall1128GLTFShape.visible = true
lv2wall1128.addComponentOrReplace(lv2wall1128GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2wall2129 = new Entity("lv2_wall(2)")
engine.addEntity(lv2wall2129)
const lv2wall2129transform = new Transform({
  position: new Vector3(15.681, 0, 0.343),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(6.872, 1.233, 1)
})
lv2wall2129.addComponentOrReplace(lv2wall2129transform)
lv2wall2129.addComponentOrReplace(lv2wall1128GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2wall3130 = new Entity("lv2_wall(3)")
engine.addEntity(lv2wall3130)
const lv2wall3130transform = new Transform({
  position: new Vector3(15.759, 0, 0.255),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(7.723709, 1.233, 1)
})
lv2wall3130.addComponentOrReplace(lv2wall3130transform)
lv2wall3130.addComponentOrReplace(lv2wall1128GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2moveableppiece4131 = new Entity("lv2_moveableppiece(4)")
engine.addEntity(lv2moveableppiece4131)
const lv2moveableppiece4131transform = new Transform({
  position: new Vector3(9.733, 1.51, 15.5),
  rotation: new Quaternion(0.4986893, -0.5013073, 0.5013073, -0.4986893),
  scale: new Vector3(1, 1, 1)
})
lv2moveableppiece4131.addComponentOrReplace(lv2moveableppiece4131transform)
lv2moveableppiece4131.addComponentOrReplace(lv2ppiece1115GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2ppiece4133 = new Entity("lv2_ppiece(4)")
engine.addEntity(lv2ppiece4133)
const lv2ppiece4133transform = new Transform({
  position: new Vector3(13.32, 3.776, 15.51),
  rotation: new Quaternion(0, 0, 0.7095708, 0.7046342),
  scale: new Vector3(1, 1, 1)
})
lv2ppiece4133.addComponentOrReplace(lv2ppiece4133transform)
lv2ppiece4133.addComponentOrReplace(lv2ppiece2118GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2ppiece5134 = new Entity("lv2_ppiece(5)")
engine.addEntity(lv2ppiece5134)
const lv2ppiece5134transform = new Transform({
  position: new Vector3(13.004, 1.501, 15.432),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
lv2ppiece5134.addComponentOrReplace(lv2ppiece5134transform)
lv2ppiece5134.addComponentOrReplace(lv2ppiece3119GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2moveableppiece3135 = new Entity("lv2_moveableppiece(3)")
engine.addEntity(lv2moveableppiece3135)
const lv2moveableppiece3135transform = new Transform({
  position: new Vector3(9.304, 4.345, 15.5),
  rotation: new Quaternion(0.7071068, 0, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
lv2moveableppiece3135.addComponentOrReplace(lv2moveableppiece3135transform)
lv2moveableppiece3135.addComponentOrReplace(lv2ppiece1115GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2moveableppiece2136 = new Entity("lv2_moveableppiece(2)")
engine.addEntity(lv2moveableppiece2136)
const lv2moveableppiece2136transform = new Transform({
  position: new Vector3(11.376, 4.187, 15.395),
  rotation: new Quaternion(-0.7071001, -0.003085315, 0.003085315, 0.7071001),
  scale: new Vector3(1, 1, 1)
})
lv2moveableppiece2136.addComponentOrReplace(lv2moveableppiece2136transform)
lv2moveableppiece2136.addComponentOrReplace(lv2moveableppiece1114GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1deadlyobstacle391 = new Entity("lv1_deadlyobstacle(3)")
engine.addEntity(lv1deadlyobstacle391)
const lv1deadlyobstacle391transform = new Transform({
  position: new Vector3(8.543, 2.947, 8),
  rotation: new Quaternion(-0.4925276, -0.5073624, -0.4925276, 0.5073624),
  scale: new Vector3(1, 1, 4.09)
})
lv1deadlyobstacle391.addComponentOrReplace(lv1deadlyobstacle391transform)
lv1deadlyobstacle391.addComponentOrReplace(lv1deadlyobstacle190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3hopper1153 = new Entity("lv3_hopper(1)")
engine.addEntity(lv3hopper1153)
const lv3hopper1153transform = new Transform({
  position: new Vector3(0.613, 4, 7.171),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 0.2, 1.5)
})
lv3hopper1153.addComponentOrReplace(lv3hopper1153transform)
const lv3hopper1153boxShape = new BoxShape()
lv3hopper1153.addComponentOrReplace(lv3hopper1153boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3hopper2154 = new Entity("lv3_hopper(2)")
engine.addEntity(lv3hopper2154)
const lv3hopper2154transform = new Transform({
  position: new Vector3(3.366, 4, 7.171),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 0.2, 1.5)
})
lv3hopper2154.addComponentOrReplace(lv3hopper2154transform)
const lv3hopper2154boxShape = new BoxShape()
lv3hopper2154.addComponentOrReplace(lv3hopper2154boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3hopper3155 = new Entity("lv3_hopper(3)")
engine.addEntity(lv3hopper3155)
const lv3hopper3155transform = new Transform({
  position: new Vector3(5.898, 4, 7.171),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 0.2, 1.5)
})
lv3hopper3155.addComponentOrReplace(lv3hopper3155transform)
const lv3hopper3155boxShape = new BoxShape()
lv3hopper3155.addComponentOrReplace(lv3hopper3155boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3hopper4156 = new Entity("lv3_hopper(4)")
engine.addEntity(lv3hopper4156)
const lv3hopper4156transform = new Transform({
  position: new Vector3(8.453, 4, 7.171),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 0.2, 1.5)
})
lv3hopper4156.addComponentOrReplace(lv3hopper4156transform)
const lv3hopper4156boxShape = new BoxShape()
lv3hopper4156.addComponentOrReplace(lv3hopper4156boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3hopper5157 = new Entity("lv3_hopper(5)")
engine.addEntity(lv3hopper5157)
const lv3hopper5157transform = new Transform({
  position: new Vector3(10.601, 4, 7.171),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 0.2, 1.5)
})
lv3hopper5157.addComponentOrReplace(lv3hopper5157transform)
const lv3hopper5157boxShape = new BoxShape()
lv3hopper5157.addComponentOrReplace(lv3hopper5157boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3hopper6158 = new Entity("lv3_hopper(6)")
engine.addEntity(lv3hopper6158)
const lv3hopper6158transform = new Transform({
  position: new Vector3(12.782, 4, 7.171),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 0.2, 1.5)
})
lv3hopper6158.addComponentOrReplace(lv3hopper6158transform)
const lv3hopper6158boxShape = new BoxShape()
lv3hopper6158.addComponentOrReplace(lv3hopper6158boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3tree2159 = new Entity("lv3_tree(2)")
engine.addEntity(lv3tree2159)
const lv3tree2159transform = new Transform({
  position: new Vector3(8.024, 0, 10.263),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
lv3tree2159.addComponentOrReplace(lv3tree2159transform)
const lv3tree2159GLTFShape = new GLTFShape("fd4168d3-1040-458d-b90e-fe5f441d593b/TreeSycamore_03/TreeSycamore_03.glb")
lv3tree2159GLTFShape.withCollisions = true
lv3tree2159GLTFShape.isPointerBlocker = true
lv3tree2159GLTFShape.visible = true
lv3tree2159.addComponentOrReplace(lv3tree2159GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3tree3162 = new Entity("lv3_tree(3)")
engine.addEntity(lv3tree3162)
const lv3tree3162transform = new Transform({
  position: new Vector3(10.637, 0, 4.397),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
lv3tree3162.addComponentOrReplace(lv3tree3162transform)
lv3tree3162.addComponentOrReplace(lv3tree2159GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0portal4167 = new Entity("lv0_portal(4)")
engine.addEntity(lv0portal4167)
const lv0portal4167transform = new Transform({
  position: new Vector3(13.96, 6.086375, 7.276),
  rotation: new Quaternion(0.4553725, -0.5120415, -0.5367531, -0.4922861),
  scale: new Vector3(2, 2, 2)
})
lv0portal4167.addComponentOrReplace(lv0portal4167transform)
const lv0portal4167GLTFShape = new GLTFShape("64c448a3-f69c-4bce-b9f4-5bb5f0669084/models/Gold_Key_Genesis.glb")
lv0portal4167GLTFShape.withCollisions = true
lv0portal4167GLTFShape.isPointerBlocker = true
lv0portal4167GLTFShape.visible = true
lv0portal4167.addComponentOrReplace(lv0portal4167GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0portal1171 = new Entity("lv0_portal(1)")
engine.addEntity(lv0portal1171)
const lv0portal1171transform = new Transform({
  position: new Vector3(14.859, 1.197, 8.352),
  rotation: new Quaternion(0, 0.6965392, 0, -0.7175187),
  scale: new Vector3(1, 1, 1)
})
lv0portal1171.addComponentOrReplace(lv0portal1171transform)
lv0portal1171.addComponentOrReplace(lv2ppiece3119GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0portal2172 = new Entity("lv0_portal(2)")
engine.addEntity(lv0portal2172)
const lv0portal2172transform = new Transform({
  position: new Vector3(14.822, 1.89, 8.472),
  rotation: new Quaternion(0.472118, -0.4911637, -0.50534, -0.5296171),
  scale: new Vector3(2, 2, 2)
})
lv0portal2172.addComponentOrReplace(lv0portal2172transform)
lv0portal2172.addComponentOrReplace(lv0portal4167GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0portal3173 = new Entity("lv0_portal(3)")
engine.addEntity(lv0portal3173)
const lv0portal3173transform = new Transform({
  position: new Vector3(14.749, 1.854, 8.358),
  rotation: new Quaternion(0.4632567, 0.5413211, -0.4902213, 0.5020435),
  scale: new Vector3(2, 2, 2)
})
lv0portal3173.addComponentOrReplace(lv0portal3173transform)
lv0portal3173.addComponentOrReplace(lv0portal4167GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1wall1174 = new Entity("lv1_wall(1)")
engine.addEntity(lv1wall1174)
const lv1wall1174transform = new Transform({
  position: new Vector3(15.142, 0.05, 15.273),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3.334, 1.223, 1)
})
lv1wall1174.addComponentOrReplace(lv1wall1174transform)
const lv1wall1174GLTFShape = new GLTFShape("5ed9c4c0-8a9c-4c0d-814c-d40354987f2b/Module_Stone_Straight_01/Module_Stone_Straight_01.glb")
lv1wall1174GLTFShape.withCollisions = true
lv1wall1174GLTFShape.isPointerBlocker = true
lv1wall1174GLTFShape.visible = true
lv1wall1174.addComponentOrReplace(lv1wall1174GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1wall4175 = new Entity("lv1_wall(4)")
engine.addEntity(lv1wall4175)
const lv1wall4175transform = new Transform({
  position: new Vector3(1.357, 0, 0.031),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(4.259, 1.223, 0.488)
})
lv1wall4175.addComponentOrReplace(lv1wall4175transform)
lv1wall4175.addComponentOrReplace(lv1wall1174GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1wall3176 = new Entity("lv1_wall(3)")
engine.addEntity(lv1wall3176)
const lv1wall3176transform = new Transform({
  position: new Vector3(15.124, 0, 0.217),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(3.849, 1.223, 1)
})
lv1wall3176.addComponentOrReplace(lv1wall3176transform)
lv1wall3176.addComponentOrReplace(lv1wall1174GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3floor179 = new Entity("lv3_floor")
engine.addEntity(lv3floor179)
const lv3floor179transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
lv3floor179.addComponentOrReplace(lv3floor179transform)
const lv3floor179GLTFShape = new GLTFShape("ea013d0a-8f70-44ca-be3d-706d46cb7ed2/FloorBaseGrass_02/FloorBaseGrass_02.glb")
lv3floor179GLTFShape.withCollisions = true
lv3floor179GLTFShape.isPointerBlocker = true
lv3floor179GLTFShape.visible = true
lv3floor179.addComponentOrReplace(lv3floor179GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1wall5184 = new Entity("lv1_wall(5)")
engine.addEntity(lv1wall5184)
const lv1wall5184transform = new Transform({
  position: new Vector3(1.823, 0, 15.273),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(4.319, 1.223, 1)
})
lv1wall5184.addComponentOrReplace(lv1wall5184transform)
lv1wall5184.addComponentOrReplace(lv1wall1174GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1wall2185 = new Entity("lv1_wall(2)")
engine.addEntity(lv1wall2185)
const lv1wall2185transform = new Transform({
  position: new Vector3(15.524, 0, 0.031),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3.543, 1.223, 0.488)
})
lv1wall2185.addComponentOrReplace(lv1wall2185transform)
lv1wall2185.addComponentOrReplace(lv1wall1174GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1floor2186 = new Entity("lv1_floor2")
engine.addEntity(lv1floor2186)
const lv1floor2186transform = new Transform({
  position: new Vector3(-8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
lv1floor2186.addComponentOrReplace(lv1floor2186transform)
lv1floor2186.addComponentOrReplace(lv1floor89GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3floor2187 = new Entity("lv3_floor2")
engine.addEntity(lv3floor2187)
const lv3floor2187transform = new Transform({
  position: new Vector3(-8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
lv3floor2187.addComponentOrReplace(lv3floor2187transform)
lv3floor2187.addComponentOrReplace(lv3floor179GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1deadlyobstacle6188 = new Entity("lv1_deadlyobstacle(6)")
engine.addEntity(lv1deadlyobstacle6188)
const lv1deadlyobstacle6188transform = new Transform({
  position: new Vector3(0.992, 2.947, 8),
  rotation: new Quaternion(-0.4925276, -0.5073624, -0.4925276, 0.5073624),
  scale: new Vector3(1, 1, 4.09)
})
lv1deadlyobstacle6188.addComponentOrReplace(lv1deadlyobstacle6188transform)
lv1deadlyobstacle6188.addComponentOrReplace(lv1deadlyobstacle190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1deadlyobstacle7189 = new Entity("lv1_deadlyobstacle(7)")
engine.addEntity(lv1deadlyobstacle7189)
const lv1deadlyobstacle7189transform = new Transform({
  position: new Vector3(-1.974, 2.947, 8),
  rotation: new Quaternion(-0.4925276, -0.5073624, -0.4925276, 0.5073624),
  scale: new Vector3(1, 1, 4.09)
})
lv1deadlyobstacle7189.addComponentOrReplace(lv1deadlyobstacle7189transform)
lv1deadlyobstacle7189.addComponentOrReplace(lv1deadlyobstacle190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1deadlyobstacle8190 = new Entity("lv1_deadlyobstacle(8)")
engine.addEntity(lv1deadlyobstacle8190)
const lv1deadlyobstacle8190transform = new Transform({
  position: new Vector3(-0.476, 2.947, 8),
  rotation: new Quaternion(-0.4925276, -0.5073624, -0.4925276, 0.5073624),
  scale: new Vector3(1, 1, 4.09)
})
lv1deadlyobstacle8190.addComponentOrReplace(lv1deadlyobstacle8190transform)
lv1deadlyobstacle8190.addComponentOrReplace(lv1deadlyobstacle190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1deadlyobstacle9191 = new Entity("lv1_deadlyobstacle(9)")
engine.addEntity(lv1deadlyobstacle9191)
const lv1deadlyobstacle9191transform = new Transform({
  position: new Vector3(-3.739, 2.947, 8),
  rotation: new Quaternion(-0.4925276, -0.5073624, -0.4925276, 0.5073624),
  scale: new Vector3(1, 1, 4.09)
})
lv1deadlyobstacle9191.addComponentOrReplace(lv1deadlyobstacle9191transform)
lv1deadlyobstacle9191.addComponentOrReplace(lv1deadlyobstacle190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1deadlyobstacle10192 = new Entity("lv1_deadlyobstacle(10)")
engine.addEntity(lv1deadlyobstacle10192)
const lv1deadlyobstacle10192transform = new Transform({
  position: new Vector3(-9.262, 2.947, 8),
  rotation: new Quaternion(-0.4925276, -0.5073624, -0.4925276, 0.5073624),
  scale: new Vector3(1, 1, 4.09)
})
lv1deadlyobstacle10192.addComponentOrReplace(lv1deadlyobstacle10192transform)
lv1deadlyobstacle10192.addComponentOrReplace(lv1deadlyobstacle190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1fence5193 = new Entity("lv1_fence(5)")
engine.addEntity(lv1fence5193)
const lv1fence5193transform = new Transform({
  position: new Vector3(-5.899, 0.171, 12.657),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(5, 5, 5)
})
lv1fence5193.addComponentOrReplace(lv1fence5193transform)
lv1fence5193.addComponentOrReplace(lv1fence297GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1fence6194 = new Entity("lv1_fence(6)")
engine.addEntity(lv1fence6194)
const lv1fence6194transform = new Transform({
  position: new Vector3(-5.899, 0.171, 7.869),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(5, 5, 5)
})
lv1fence6194.addComponentOrReplace(lv1fence6194transform)
lv1fence6194.addComponentOrReplace(lv1fence297GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1fence7195 = new Entity("lv1_fence(7)")
engine.addEntity(lv1fence7195)
const lv1fence7195transform = new Transform({
  position: new Vector3(-5.899, 0.171, 3.713),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(5, 5, 5)
})
lv1fence7195.addComponentOrReplace(lv1fence7195transform)
lv1fence7195.addComponentOrReplace(lv1fence297GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1deadlyobstacle11196 = new Entity("lv1_deadlyobstacle(11)")
engine.addEntity(lv1deadlyobstacle11196)
const lv1deadlyobstacle11196transform = new Transform({
  position: new Vector3(-11.09, 2.947, 8),
  rotation: new Quaternion(-0.4925276, -0.5073624, -0.4925276, 0.5073624),
  scale: new Vector3(1, 1, 4.09)
})
lv1deadlyobstacle11196.addComponentOrReplace(lv1deadlyobstacle11196transform)
lv1deadlyobstacle11196.addComponentOrReplace(lv1deadlyobstacle190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0wall4197 = new Entity("lv0_wall(4)")
engine.addEntity(lv0wall4197)
const lv0wall4197transform = new Transform({
  position: new Vector3(-6.629, 2.5, 0.118),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(15, 5, 0.15)
})
lv0wall4197.addComponentOrReplace(lv0wall4197transform)
const lv0wall4197boxShape = new BoxShape()
lv0wall4197.addComponentOrReplace(lv0wall4197boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0wall5198 = new Entity("lv0_wall(5)")
engine.addEntity(lv0wall5198)
const lv0wall5198transform = new Transform({
  position: new Vector3(-6.608, 2.5, 15.901),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(15, 5, 0.15)
})
lv0wall5198.addComponentOrReplace(lv0wall5198transform)
const lv0wall5198boxShape = new BoxShape()
lv0wall5198.addComponentOrReplace(lv0wall5198boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1fence8199 = new Entity("lv1_fence(8)")
engine.addEntity(lv1fence8199)
const lv1fence8199transform = new Transform({
  position: new Vector3(0.614, 0.171, 2.187),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 5, 18.738)
})
lv1fence8199.addComponentOrReplace(lv1fence8199transform)
lv1fence8199.addComponentOrReplace(lv1fence297GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1fence9200 = new Entity("lv1_fence(9)")
engine.addEntity(lv1fence9200)
const lv1fence9200transform = new Transform({
  position: new Vector3(0.143, 0.171, 13.487),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 5, 18.738)
})
lv1fence9200.addComponentOrReplace(lv1fence9200transform)
lv1fence9200.addComponentOrReplace(lv1fence297GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1fence10201 = new Entity("lv1_fence(10)")
engine.addEntity(lv1fence10201)
const lv1fence10201transform = new Transform({
  position: new Vector3(10.534, 0.171, 14.009),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 5, 12.422)
})
lv1fence10201.addComponentOrReplace(lv1fence10201transform)
lv1fence10201.addComponentOrReplace(lv1fence297GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv1fence11202 = new Entity("lv1_fence(11)")
engine.addEntity(lv1fence11202)
const lv1fence11202transform = new Transform({
  position: new Vector3(11.392, 0.171, 1.558),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 5, 12.422)
})
lv1fence11202.addComponentOrReplace(lv1fence11202transform)
lv1fence11202.addComponentOrReplace(lv1fence297GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2wall5203 = new Entity("lv2_wall(5)")
engine.addEntity(lv2wall5203)
const lv2wall5203transform = new Transform({
  position: new Vector3(1.934, 0, 0.343),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(6.872, 1.233, 1)
})
lv2wall5203.addComponentOrReplace(lv2wall5203transform)
lv2wall5203.addComponentOrReplace(lv2wall1128GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2wall4204 = new Entity("lv2_wall(4)")
engine.addEntity(lv2wall4204)
const lv2wall4204transform = new Transform({
  position: new Vector3(2.147, 0, 15.854),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(6.872, 1.233, 1)
})
lv2wall4204.addComponentOrReplace(lv2wall4204transform)
lv2wall4204.addComponentOrReplace(lv2wall1128GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3hopper7206 = new Entity("lv3_hopper(7)")
engine.addEntity(lv3hopper7206)
const lv3hopper7206transform = new Transform({
  position: new Vector3(-2.094, 4, 7.171),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 0.2, 1.5)
})
lv3hopper7206.addComponentOrReplace(lv3hopper7206transform)
const lv3hopper7206boxShape = new BoxShape()
lv3hopper7206.addComponentOrReplace(lv3hopper7206boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3hopper8207 = new Entity("lv3_hopper(8)")
engine.addEntity(lv3hopper8207)
const lv3hopper8207transform = new Transform({
  position: new Vector3(-4.684, 4, 7.171),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 0.2, 1.5)
})
lv3hopper8207.addComponentOrReplace(lv3hopper8207transform)
const lv3hopper8207boxShape = new BoxShape()
lv3hopper8207.addComponentOrReplace(lv3hopper8207boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3hopper9208 = new Entity("lv3_hopper(9)")
engine.addEntity(lv3hopper9208)
const lv3hopper9208transform = new Transform({
  position: new Vector3(-7.015, 4, 7.171),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 0.2, 1.5)
})
lv3hopper9208.addComponentOrReplace(lv3hopper9208transform)
const lv3hopper9208boxShape = new BoxShape()
lv3hopper9208.addComponentOrReplace(lv3hopper9208boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3hopper10209 = new Entity("lv3_hopper(10)")
engine.addEntity(lv3hopper10209)
const lv3hopper10209transform = new Transform({
  position: new Vector3(-9.392, 4, 7.171),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 0.2, 1.5)
})
lv3hopper10209.addComponentOrReplace(lv3hopper10209transform)
const lv3hopper10209boxShape = new BoxShape()
lv3hopper10209.addComponentOrReplace(lv3hopper10209boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv3elevator210 = new Entity("lv3_elevator")
engine.addEntity(lv3elevator210)
const lv3elevator210transform = new Transform({
  position: new Vector3(-11.64, 1.169, 7.171),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 0.2, 1.5)
})
lv3elevator210.addComponentOrReplace(lv3elevator210transform)
const lv3elevator210boxShape = new BoxShape()
lv3elevator210.addComponentOrReplace(lv3elevator210boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2moveableppiece6211 = new Entity("lv2_moveableppiece(6)")
engine.addEntity(lv2moveableppiece6211)
const lv2moveableppiece6211transform = new Transform({
  position: new Vector3(8.676, 4.681, 0.3),
  rotation: new Quaternion(-3.090862E-08, -0.7071068, -0.7071068, 3.090862E-08),
  scale: new Vector3(1, 1, 1)
})
lv2moveableppiece6211.addComponentOrReplace(lv2moveableppiece6211transform)
lv2moveableppiece6211.addComponentOrReplace(lv2ppiece1115GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2moveableppiece7212 = new Entity("lv2_moveableppiece(7)")
engine.addEntity(lv2moveableppiece7212)
const lv2moveableppiece7212transform = new Transform({
  position: new Vector3(6.691, 4.455, 0.3),
  rotation: new Quaternion(0.5, -0.5, -0.5, 0.5),
  scale: new Vector3(1, 1, 1)
})
lv2moveableppiece7212.addComponentOrReplace(lv2moveableppiece7212transform)
lv2moveableppiece7212.addComponentOrReplace(lv2moveableppiece1114GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2ppiece8213 = new Entity("lv2_ppiece(8)")
engine.addEntity(lv2ppiece8213)
const lv2ppiece8213transform = new Transform({
  position: new Vector3(4.999, 4.421, 0.29),
  rotation: new Quaternion(0.7071068, 0, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
lv2ppiece8213.addComponentOrReplace(lv2ppiece8213transform)
const lv2ppiece8213GLTFShape = new GLTFShape("e6f54515-1149-4c8d-af15-d59ffd7d27a5/LightCross_02/LightCross_02.glb")
lv2ppiece8213GLTFShape.withCollisions = true
lv2ppiece8213GLTFShape.isPointerBlocker = true
lv2ppiece8213GLTFShape.visible = true
lv2ppiece8213.addComponentOrReplace(lv2ppiece8213GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2moveableppiece8214 = new Entity("lv2_moveableppiece(8)")
engine.addEntity(lv2moveableppiece8214)
const lv2moveableppiece8214transform = new Transform({
  position: new Vector3(5.283, 2.469, 0.604),
  rotation: new Quaternion(0.5, 0.5, 0.5, 0.5),
  scale: new Vector3(1, 1, 1)
})
lv2moveableppiece8214.addComponentOrReplace(lv2moveableppiece8214transform)
lv2moveableppiece8214.addComponentOrReplace(lv2ppiece1115GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2ppiece7215 = new Entity("lv2_ppiece(7)")
engine.addEntity(lv2ppiece7215)
const lv2ppiece7215transform = new Transform({
  position: new Vector3(3.112, 1.957, 0.431),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
lv2ppiece7215.addComponentOrReplace(lv2ppiece7215transform)
lv2ppiece7215.addComponentOrReplace(lv2ppiece3119GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2charger216 = new Entity("lv2_charger")
engine.addEntity(lv2charger216)
const lv2charger216transform = new Transform({
  position: new Vector3(3.047, 0.275, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3.21, 3)
})
lv2charger216.addComponentOrReplace(lv2charger216transform)
const lv2charger216GLTFShape = new GLTFShape("feb2e4fd-c6f2-41ae-9968-0f3d87e8b55f/Charger_01/Charger_01.glb")
lv2charger216GLTFShape.withCollisions = true
lv2charger216GLTFShape.isPointerBlocker = true
lv2charger216GLTFShape.visible = true
lv2charger216.addComponentOrReplace(lv2charger216GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2cable1217 = new Entity("lv2_cable1")
engine.addEntity(lv2cable1217)
const lv2cable1217transform = new Transform({
  position: new Vector3(3.125, 2.297, 7.283),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1.712, 0.5, 0.5)
})
lv2cable1217.addComponentOrReplace(lv2cable1217transform)
const lv2cable1217GLTFShape = new GLTFShape("6ac60649-7f9d-4426-9329-e73275e63472/AirVent_Straight_Long_01/AirVent_Straight_Long_01.glb")
lv2cable1217GLTFShape.withCollisions = true
lv2cable1217GLTFShape.isPointerBlocker = true
lv2cable1217GLTFShape.visible = true
lv2cable1217.addComponentOrReplace(lv2cable1217GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2cable2218 = new Entity("lv2_cable2")
engine.addEntity(lv2cable2218)
const lv2cable2218transform = new Transform({
  position: new Vector3(3.125, 2.297, 15.225),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1.643, 0.5, 0.5)
})
lv2cable2218.addComponentOrReplace(lv2cable2218transform)
lv2cable2218.addComponentOrReplace(lv2cable1217GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2ppiece9219 = new Entity("lv2_ppiece(9)")
engine.addEntity(lv2ppiece9219)
const lv2ppiece9219transform = new Transform({
  position: new Vector3(3.112, 1.957, 15.195),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
lv2ppiece9219.addComponentOrReplace(lv2ppiece9219transform)
lv2ppiece9219.addComponentOrReplace(lv2ppiece3119GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2moveableppiece9220 = new Entity("lv2_moveableppiece(9)")
engine.addEntity(lv2moveableppiece9220)
const lv2moveableppiece9220transform = new Transform({
  position: new Vector3(5.18, 2.802, 15.5),
  rotation: new Quaternion(0.5, 0.5, -0.5, -0.5),
  scale: new Vector3(1, 1, 1)
})
lv2moveableppiece9220.addComponentOrReplace(lv2moveableppiece9220transform)
lv2moveableppiece9220.addComponentOrReplace(lv2ppiece1115GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2moveableppiece10221 = new Entity("lv2_moveableppiece(10)")
engine.addEntity(lv2moveableppiece10221)
const lv2moveableppiece10221transform = new Transform({
  position: new Vector3(4.769, 0.207, 15.5),
  rotation: new Quaternion(-3.090862E-08, 0.7071068, -0.7071068, -3.090862E-08),
  scale: new Vector3(1, 1, 1)
})
lv2moveableppiece10221.addComponentOrReplace(lv2moveableppiece10221transform)
lv2moveableppiece10221.addComponentOrReplace(lv2ppiece1115GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2moveableppiece11222 = new Entity("lv2_moveableppiece(11)")
engine.addEntity(lv2moveableppiece11222)
const lv2moveableppiece11222transform = new Transform({
  position: new Vector3(7.425, 0.207, 15.5),
  rotation: new Quaternion(0.0006170832, 0.7071065, -0.7071065, 0.0006170832),
  scale: new Vector3(1, 1, 1)
})
lv2moveableppiece11222.addComponentOrReplace(lv2moveableppiece11222transform)
lv2moveableppiece11222.addComponentOrReplace(lv2ppiece1115GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv2ppiece10223 = new Entity("lv2_ppiece(10)")
engine.addEntity(lv2ppiece10223)
const lv2ppiece10223transform = new Transform({
  position: new Vector3(7.738, 1.744, 15.509),
  rotation: new Quaternion(0.5, 0.5, -0.5, -0.5),
  scale: new Vector3(1, 1, 1)
})
lv2ppiece10223.addComponentOrReplace(lv2ppiece10223transform)
lv2ppiece10223.addComponentOrReplace(lv2moveableppiece1114GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0link227 = new Entity("lv0_link")
engine.addEntity(lv0link227)
const lv0link227transform = new Transform({
  position: new Vector3(-10.402, 0.085, 13.372),
  rotation: new Quaternion(0, 1, 0, -4.371139E-08),
  scale: new Vector3(2, 2, 2)
})
lv0link227.addComponentOrReplace(lv0link227transform)
const lv0link227GLTFShape = new GLTFShape("8dcc2ca4-5e30-4488-9731-be24f0c041fd/models/discord.glb")
lv0link227GLTFShape.withCollisions = true
lv0link227GLTFShape.isPointerBlocker = true
lv0link227GLTFShape.visible = true
lv0link227.addComponentOrReplace(lv0link227GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0banner229 = new Entity("lv0_banner")
engine.addEntity(lv0banner229)
const lv0banner229transform = new Transform({
  position: new Vector3(-10.439, 2.905, 14.823),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(3, 3, 0.058)
})
lv0banner229.addComponentOrReplace(lv0banner229transform)
const lv0banner229boxShape = new BoxShape()
lv0banner229.addComponentOrReplace(lv0banner229boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lv0banner1230 = new Entity("lv0_banner1")
engine.addEntity(lv0banner1230)
const lv0banner1230transform = new Transform({
  position: new Vector3(-10.44245, 2.905, 14.861),
  rotation: new Quaternion(0, 1, 0, -4.371139E-08),
  scale: new Vector3(3, 3, 0.058)
})
lv0banner1230.addComponentOrReplace(lv0banner1230transform)
const lv0banner1230boxShape = new BoxShape()
lv0banner1230.addComponentOrReplace(lv0banner1230boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
  lv0wall1:{
    entity: lv0wall110,
    transform: lv0wall110transform,
    boxShape: lv0wall110boxShape,
  },
  lv0wall2:{
    entity: lv0wall211,
    transform: lv0wall211transform,
    boxShape: lv0wall211boxShape,
  },
  lv0wall3:{
    entity: lv0wall312,
    transform: lv0wall312transform,
    boxShape: lv0wall312boxShape,
  },
  lv1return:{
    entity: lv1return87,
    transform: lv1return87transform,
    GLTFShape: lv1return87GLTFShape,
  },
  lv1floor:{
    entity: lv1floor89,
    transform: lv1floor89transform,
    GLTFShape: lv1floor89GLTFShape,
  },
  lv1deadlyobstacle1:{
    entity: lv1deadlyobstacle190,
    transform: lv1deadlyobstacle190transform,
    GLTFShape: lv1deadlyobstacle190GLTFShape,
  },
  lv1deadlyobstacle4:{
    entity: lv1deadlyobstacle492,
    transform: lv1deadlyobstacle492transform,
    GLTFShape: lv1deadlyobstacle190GLTFShape,
  },
  lv1deadlyobstacle2:{
    entity: lv1deadlyobstacle293,
    transform: lv1deadlyobstacle293transform,
    GLTFShape: lv1deadlyobstacle190GLTFShape,
  },
  lv1deadlyobstacle5:{
    entity: lv1deadlyobstacle594,
    transform: lv1deadlyobstacle594transform,
    GLTFShape: lv1deadlyobstacle190GLTFShape,
  },
  lv1fence2:{
    entity: lv1fence297,
    transform: lv1fence297transform,
    GLTFShape: lv1fence297GLTFShape,
  },
  lv1fence1:{
    entity: lv1fence199,
    transform: lv1fence199transform,
    GLTFShape: lv1fence297GLTFShape,
  },
  lv1fence4:{
    entity: lv1fence4100,
    transform: lv1fence4100transform,
    GLTFShape: lv1fence297GLTFShape,
  },
  lv1fence3:{
    entity: lv1fence3101,
    transform: lv1fence3101transform,
    GLTFShape: lv1fence297GLTFShape,
  },
  lv2moveableppiece1:{
    entity: lv2moveableppiece1114,
    transform: lv2moveableppiece1114transform,
    GLTFShape: lv2moveableppiece1114GLTFShape,
  },
  lv2ppiece1:{
    entity: lv2ppiece1115,
    transform: lv2ppiece1115transform,
    GLTFShape: lv2ppiece1115GLTFShape,
  },
  lv2ppiece2:{
    entity: lv2ppiece2118,
    transform: lv2ppiece2118transform,
    GLTFShape: lv2ppiece2118GLTFShape,
  },
  lv2ppiece3:{
    entity: lv2ppiece3119,
    transform: lv2ppiece3119transform,
    GLTFShape: lv2ppiece3119GLTFShape,
  },
  lv2wall1:{
    entity: lv2wall1128,
    transform: lv2wall1128transform,
    GLTFShape: lv2wall1128GLTFShape,
  },
  lv2wall2:{
    entity: lv2wall2129,
    transform: lv2wall2129transform,
    GLTFShape: lv2wall1128GLTFShape,
  },
  lv2wall3:{
    entity: lv2wall3130,
    transform: lv2wall3130transform,
    GLTFShape: lv2wall1128GLTFShape,
  },
  lv2moveableppiece4:{
    entity: lv2moveableppiece4131,
    transform: lv2moveableppiece4131transform,
    GLTFShape: lv2ppiece1115GLTFShape,
  },
  lv2ppiece4:{
    entity: lv2ppiece4133,
    transform: lv2ppiece4133transform,
    GLTFShape: lv2ppiece2118GLTFShape,
  },
  lv2ppiece5:{
    entity: lv2ppiece5134,
    transform: lv2ppiece5134transform,
    GLTFShape: lv2ppiece3119GLTFShape,
  },
  lv2moveableppiece3:{
    entity: lv2moveableppiece3135,
    transform: lv2moveableppiece3135transform,
    GLTFShape: lv2ppiece1115GLTFShape,
  },
  lv2moveableppiece2:{
    entity: lv2moveableppiece2136,
    transform: lv2moveableppiece2136transform,
    GLTFShape: lv2moveableppiece1114GLTFShape,
  },
  lv1deadlyobstacle3:{
    entity: lv1deadlyobstacle391,
    transform: lv1deadlyobstacle391transform,
    GLTFShape: lv1deadlyobstacle190GLTFShape,
  },
  lv3hopper1:{
    entity: lv3hopper1153,
    transform: lv3hopper1153transform,
    boxShape: lv3hopper1153boxShape,
  },
  lv3hopper2:{
    entity: lv3hopper2154,
    transform: lv3hopper2154transform,
    boxShape: lv3hopper2154boxShape,
  },
  lv3hopper3:{
    entity: lv3hopper3155,
    transform: lv3hopper3155transform,
    boxShape: lv3hopper3155boxShape,
  },
  lv3hopper4:{
    entity: lv3hopper4156,
    transform: lv3hopper4156transform,
    boxShape: lv3hopper4156boxShape,
  },
  lv3hopper5:{
    entity: lv3hopper5157,
    transform: lv3hopper5157transform,
    boxShape: lv3hopper5157boxShape,
  },
  lv3hopper6:{
    entity: lv3hopper6158,
    transform: lv3hopper6158transform,
    boxShape: lv3hopper6158boxShape,
  },
  lv3tree2:{
    entity: lv3tree2159,
    transform: lv3tree2159transform,
    GLTFShape: lv3tree2159GLTFShape,
  },
  lv3tree3:{
    entity: lv3tree3162,
    transform: lv3tree3162transform,
    GLTFShape: lv3tree2159GLTFShape,
  },
  lv0portal4:{
    entity: lv0portal4167,
    transform: lv0portal4167transform,
    GLTFShape: lv0portal4167GLTFShape,
  },
  lv0portal1:{
    entity: lv0portal1171,
    transform: lv0portal1171transform,
    GLTFShape: lv2ppiece3119GLTFShape,
  },
  lv0portal2:{
    entity: lv0portal2172,
    transform: lv0portal2172transform,
    GLTFShape: lv0portal4167GLTFShape,
  },
  lv0portal3:{
    entity: lv0portal3173,
    transform: lv0portal3173transform,
    GLTFShape: lv0portal4167GLTFShape,
  },
  lv1wall1:{
    entity: lv1wall1174,
    transform: lv1wall1174transform,
    GLTFShape: lv1wall1174GLTFShape,
  },
  lv1wall4:{
    entity: lv1wall4175,
    transform: lv1wall4175transform,
    GLTFShape: lv1wall1174GLTFShape,
  },
  lv1wall3:{
    entity: lv1wall3176,
    transform: lv1wall3176transform,
    GLTFShape: lv1wall1174GLTFShape,
  },
  lv3floor:{
    entity: lv3floor179,
    transform: lv3floor179transform,
    GLTFShape: lv3floor179GLTFShape,
  },
  lv1wall5:{
    entity: lv1wall5184,
    transform: lv1wall5184transform,
    GLTFShape: lv1wall1174GLTFShape,
  },
  lv1wall2:{
    entity: lv1wall2185,
    transform: lv1wall2185transform,
    GLTFShape: lv1wall1174GLTFShape,
  },
  lv1floor2:{
    entity: lv1floor2186,
    transform: lv1floor2186transform,
    GLTFShape: lv1floor89GLTFShape,
  },
  lv3floor2:{
    entity: lv3floor2187,
    transform: lv3floor2187transform,
    GLTFShape: lv3floor179GLTFShape,
  },
  lv1deadlyobstacle6:{
    entity: lv1deadlyobstacle6188,
    transform: lv1deadlyobstacle6188transform,
    GLTFShape: lv1deadlyobstacle190GLTFShape,
  },
  lv1deadlyobstacle7:{
    entity: lv1deadlyobstacle7189,
    transform: lv1deadlyobstacle7189transform,
    GLTFShape: lv1deadlyobstacle190GLTFShape,
  },
  lv1deadlyobstacle8:{
    entity: lv1deadlyobstacle8190,
    transform: lv1deadlyobstacle8190transform,
    GLTFShape: lv1deadlyobstacle190GLTFShape,
  },
  lv1deadlyobstacle9:{
    entity: lv1deadlyobstacle9191,
    transform: lv1deadlyobstacle9191transform,
    GLTFShape: lv1deadlyobstacle190GLTFShape,
  },
  lv1deadlyobstacle10:{
    entity: lv1deadlyobstacle10192,
    transform: lv1deadlyobstacle10192transform,
    GLTFShape: lv1deadlyobstacle190GLTFShape,
  },
  lv1fence5:{
    entity: lv1fence5193,
    transform: lv1fence5193transform,
    GLTFShape: lv1fence297GLTFShape,
  },
  lv1fence6:{
    entity: lv1fence6194,
    transform: lv1fence6194transform,
    GLTFShape: lv1fence297GLTFShape,
  },
  lv1fence7:{
    entity: lv1fence7195,
    transform: lv1fence7195transform,
    GLTFShape: lv1fence297GLTFShape,
  },
  lv1deadlyobstacle11:{
    entity: lv1deadlyobstacle11196,
    transform: lv1deadlyobstacle11196transform,
    GLTFShape: lv1deadlyobstacle190GLTFShape,
  },
  lv0wall4:{
    entity: lv0wall4197,
    transform: lv0wall4197transform,
    boxShape: lv0wall4197boxShape,
  },
  lv0wall5:{
    entity: lv0wall5198,
    transform: lv0wall5198transform,
    boxShape: lv0wall5198boxShape,
  },
  lv1fence8:{
    entity: lv1fence8199,
    transform: lv1fence8199transform,
    GLTFShape: lv1fence297GLTFShape,
  },
  lv1fence9:{
    entity: lv1fence9200,
    transform: lv1fence9200transform,
    GLTFShape: lv1fence297GLTFShape,
  },
  lv1fence10:{
    entity: lv1fence10201,
    transform: lv1fence10201transform,
    GLTFShape: lv1fence297GLTFShape,
  },
  lv1fence11:{
    entity: lv1fence11202,
    transform: lv1fence11202transform,
    GLTFShape: lv1fence297GLTFShape,
  },
  lv2wall5:{
    entity: lv2wall5203,
    transform: lv2wall5203transform,
    GLTFShape: lv2wall1128GLTFShape,
  },
  lv2wall4:{
    entity: lv2wall4204,
    transform: lv2wall4204transform,
    GLTFShape: lv2wall1128GLTFShape,
  },
  lv3hopper7:{
    entity: lv3hopper7206,
    transform: lv3hopper7206transform,
    boxShape: lv3hopper7206boxShape,
  },
  lv3hopper8:{
    entity: lv3hopper8207,
    transform: lv3hopper8207transform,
    boxShape: lv3hopper8207boxShape,
  },
  lv3hopper9:{
    entity: lv3hopper9208,
    transform: lv3hopper9208transform,
    boxShape: lv3hopper9208boxShape,
  },
  lv3hopper10:{
    entity: lv3hopper10209,
    transform: lv3hopper10209transform,
    boxShape: lv3hopper10209boxShape,
  },
  lv3elevator:{
    entity: lv3elevator210,
    transform: lv3elevator210transform,
    boxShape: lv3elevator210boxShape,
  },
  lv2moveableppiece6:{
    entity: lv2moveableppiece6211,
    transform: lv2moveableppiece6211transform,
    GLTFShape: lv2ppiece1115GLTFShape,
  },
  lv2moveableppiece7:{
    entity: lv2moveableppiece7212,
    transform: lv2moveableppiece7212transform,
    GLTFShape: lv2moveableppiece1114GLTFShape,
  },
  lv2ppiece8:{
    entity: lv2ppiece8213,
    transform: lv2ppiece8213transform,
    GLTFShape: lv2ppiece8213GLTFShape,
  },
  lv2moveableppiece8:{
    entity: lv2moveableppiece8214,
    transform: lv2moveableppiece8214transform,
    GLTFShape: lv2ppiece1115GLTFShape,
  },
  lv2ppiece7:{
    entity: lv2ppiece7215,
    transform: lv2ppiece7215transform,
    GLTFShape: lv2ppiece3119GLTFShape,
  },
  lv2charger:{
    entity: lv2charger216,
    transform: lv2charger216transform,
    GLTFShape: lv2charger216GLTFShape,
  },
  lv2cable1:{
    entity: lv2cable1217,
    transform: lv2cable1217transform,
    GLTFShape: lv2cable1217GLTFShape,
  },
  lv2cable2:{
    entity: lv2cable2218,
    transform: lv2cable2218transform,
    GLTFShape: lv2cable1217GLTFShape,
  },
  lv2ppiece9:{
    entity: lv2ppiece9219,
    transform: lv2ppiece9219transform,
    GLTFShape: lv2ppiece3119GLTFShape,
  },
  lv2moveableppiece9:{
    entity: lv2moveableppiece9220,
    transform: lv2moveableppiece9220transform,
    GLTFShape: lv2ppiece1115GLTFShape,
  },
  lv2moveableppiece10:{
    entity: lv2moveableppiece10221,
    transform: lv2moveableppiece10221transform,
    GLTFShape: lv2ppiece1115GLTFShape,
  },
  lv2moveableppiece11:{
    entity: lv2moveableppiece11222,
    transform: lv2moveableppiece11222transform,
    GLTFShape: lv2ppiece1115GLTFShape,
  },
  lv2ppiece10:{
    entity: lv2ppiece10223,
    transform: lv2ppiece10223transform,
    GLTFShape: lv2moveableppiece1114GLTFShape,
  },
  lv0link:{
    entity: lv0link227,
    transform: lv0link227transform,
    GLTFShape: lv0link227GLTFShape,
  },
  lv0banner:{
    entity: lv0banner229,
    transform: lv0banner229transform,
    boxShape: lv0banner229boxShape,
  },
  lv0banner1:{
    entity: lv0banner1230,
    transform: lv0banner1230transform,
    boxShape: lv0banner1230boxShape,
  },
}

